# Generated by Django 6.0.4 on 2026-04-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_mediaitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
